"""
Parallelization Module: Voting Workflow for Video Question Answering

This module implements a parallelization workflow that reads questions from a CSV file and video section descriptions from a JSON file. It generates answers for different video sections in parallel using Gemini 2.0 Flash, aggregates them, and saves the final aggregated answer for each question (identified by qid) in a new CSV file. It also logs video IDs that are not found in the JSON file into a text file.
"""

import os
import json
import csv
import concurrent.futures
from dotenv import load_dotenv  # Loads environment variables from a .env file
import google.generativeai as genai  # Gemini API library for video understanding

# Load environment variables and configure Gemini API
load_dotenv()
api_key = os.getenv("GEMINI_API_KEY")
if not api_key:
    raise ValueError("GEMINI_API_KEY not found in environment variables")
genai.configure(api_key=api_key)


def generate_answer(input_data):
    """
    Generate an answer using the Gemini 2.0 Flash model.

    Parameters:
        input_data (list): A list containing the prompt string.

    Returns:
        str: The generated answer text from the model.
    """
    model = genai.GenerativeModel(
        model_name="models/gemini-2.0-flash",
        generation_config={"temperature": 0.5},  # Using Gemini 2.0 Flash
    )
    response = model.generate_content(input_data, request_options={"timeout": 600})
    try:
        output = response.text.strip()
    except Exception as e:
        print(f"Error generating answer: {str(e)}")
        output = ""
    return output


def answer_section(section_label, section_description, question, question_prompt):
    """
    Generate an answer for a single video section using the provided description.

    Parameters:
        section_label (str): Label for the video section (e.g., 'Full Video', 'Front Section').
        section_description (str): Description text for the video section.
        question (str): The question to be answered.
        question_prompt (str): Additional prompt context for the question.

    Returns:
        str: The answer generated by the LLM for the section.
    """
    prompt_text = (
        f"Question: {question}\n"
        f"Question Prompt: {question_prompt}\n"
        f"Video Section ({section_label}) Description: {section_description}\n"
        "Answer:"
    )
    input_data = [prompt_text]
    return generate_answer(input_data)


def aggregate_answers(question, question_prompt, answers):
    """
    Aggregates answers from different video sections to produce the final answer.

    Parameters:
        question (str): The original question.
        question_prompt (str): Additional prompt context for the question.
        answers (list): List of answers from the different video sections.

    Returns:
        str: The aggregated final answer.
    """
    section_names = ["Full Video", "Front Section", "Middle Section", "End Section"]
    aggregator_prompt = (
        f"Question: {question}\nHere are the answers from different video sections:\n"
    )
    for name, ans in zip(section_names, answers):
        aggregator_prompt += f"{name} Answer: {ans}\n"
    aggregator_prompt += f"Please aggregate the above answers based on the Question, reconcile any differences, and only use the context from the video sections for your final answer. In your output, answer the question directly. {question_prompt}"

    """example input data:
    Question: What is the main theme of the video?
    
    Here are the answers from different video sections:
    "Full Video" Answer: The video is about the history of space exploration.
    "Front Section" Answer: The video discusses the early missions to the moon.
    "Middle Section" Answer: The video covers the development of space telescopes.
    "End Section" Answer: The video concludes with a discussion on future Mars missions.
    """
    input_data = [aggregator_prompt]
    return generate_answer(input_data)


def process_parallel_questions(
    challenge_csv="challenge_data.csv",
    partial_json="partial_understanding.json",
    output_csv="parallel_output.csv",
    failed_videos_file="failed_videos.txt",
):
    """
    Process questions from a CSV file and generate aggregated answers using video descriptions.

    This function performs the following steps:
    1. Loads video descriptions from a JSON file (partial_understanding.json).
    2. Reads each question along with its qid and video_id from challenge_data.csv.
    3. For each video, retrieves the full and sectional descriptions.
    4. Uses a parallelized workflow to generate answers for each section using Gemini 2.0 Flash.
    5. Aggregates the answers via a voting process using another Gemini call.
    6. Saves the final aggregated answers into a CSV file with columns: qid and answer.
    7. Logs any video_ids that are not found in the JSON file into a text file.

    Parameters:
        challenge_csv (str): Path to the CSV file with questions, qid, and video IDs.
        partial_json (str): Path to the JSON file with video descriptions.
        output_csv (str): Path for the output CSV file to store final aggregated answers.
        failed_videos_file (str): Path for the text file to log failed video IDs.
    """
    # Load the partial understanding JSON file
    with open(partial_json, "r") as f:
        partial_data = json.load(f)

    results = []  # List to store results with keys 'qid' and 'answer'
    failed_videos = []  # List to store video_ids not found in the JSON

    # Read questions from the CSV file
    # utf-8-sig resolves a weird issue where qid is "\ufeffqid" instead of "qid"
    with open(challenge_csv, "r", encoding="utf-8-sig") as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            qid = row.get("qid", "").strip()
            video_id = row.get("video_id", "").strip()
            question = row.get("question", "").strip()
            question_prompt = (
                row.get("question_prompt", "").strip()
                + "If the description does not answer the question, describe the details of the video section and how it might answer the question."
            )

            if not video_id or video_id not in partial_data:
                print(
                    f"Video ID {video_id} not found in partial understanding data for qid {qid}."
                )
                failed_videos.append(video_id)
                continue

            video_info = partial_data[video_id]
            full_desc = video_info.get(f"{video_id}_0", "")
            front_desc = video_info.get(f"{video_id}_1", "")
            middle_desc = video_info.get(f"{video_id}_2", "")
            end_desc = video_info.get(f"{video_id}_3", "")

            # Prepare to collect answers from different sections in parallel
            answers = [None] * 4
            with concurrent.futures.ThreadPoolExecutor() as executor:
                future_to_section = {
                    executor.submit(
                        answer_section,
                        "Full Video",
                        full_desc,
                        question,
                        question_prompt,
                    ): 0,
                    executor.submit(
                        answer_section,
                        "Front Section",
                        front_desc,
                        question,
                        question_prompt,
                    ): 1,
                    executor.submit(
                        answer_section,
                        "Middle Section",
                        middle_desc,
                        question,
                        question_prompt,
                    ): 2,
                    executor.submit(
                        answer_section,
                        "End Section",
                        end_desc,
                        question,
                        question_prompt,
                    ): 3,
                }
                for future in concurrent.futures.as_completed(future_to_section):
                    idx = future_to_section[future]
                    try:
                        answer_result = future.result()
                    except Exception as exc:
                        print(f"Section processing generated an exception: {exc}")
                        answer_result = ""
                    answers[idx] = answer_result
            print(f"Partial answers generated for qid {qid}")
            # print(answers)
            # Aggregate the answers using a "voting" mechanism
            aggregated_answer = aggregate_answers(question, question_prompt, answers)
            print(f"Aggregated answer for qid {qid}")
            # print(f"{aggregated_answer}\n")
            # Append result with qid and aggregated answer
            results.append({"qid": qid, "answer": aggregated_answer})

    # Write failed videos list to a text file as a JSON list
    with open(failed_videos_file, "w") as f:
        json.dump(failed_videos, f, indent=4)

    # Write the final results to a CSV file with columns: qid and answer
    with open(output_csv, "w", newline="") as csvfile:
        fieldnames = ["qid", "pred"]
        writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
        writer.writeheader()
        for entry in results:
            writer.writerow(entry)

    print(f"Final aggregated answers saved to {output_csv}")
    print(f"Failed video IDs saved to {failed_videos_file}")


if __name__ == "__main__":
    process_parallel_questions()
